config/routes.rb
Leadgen::Application.routes.draw do

  post "users/send_message" => "users#send_message"
  resources :users
  resources :charges
  

  root :to => 'questions#new'
  get "logout" => "sessions#destroy", :as => "logout"
  get "login" => "sessions#new", :as => "login"
  get "signup" => "users#new", :as => "signup"
  resources :sessions
  get "secret" => "home#secret", :as => "secret"
  get 'tags/:tag', to: 'questions#index', as: :tag

  resources :questions do
    post "payments/create"
  end

end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  attr_accessible :payment, :question_id
end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :description, :email, :name, :phone, :response, :latitude, :longitude, :ip_address, :tag_list
  has_many :payments
  has_many :users, :through => :payments
  geocoded_by :ip_address
  after_validation :geocode
  acts_as_taggable
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessible :title, :body
  authenticates_with_sorcery!
  has_many :payments
  has_many :questions, :through => :payments


  attr_accessible :email, :password, :password_confirmation

  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :require_login
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end


def create
  @user = current_user
  @user.balance += 10



  # Amount in cents
  @amount = 1000

  customer = Stripe::Customer.create(
    :email => current_user.email,
    :card  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'cad'
  )
  if @user.save
    redirect_to questions_path, :notice => "Thank you for adding money to your account!"
  else
    render :edit
  end

  rescue Stripe::CardError => e
    flash[:notice] = e.message
    redirect_to questions_path, :notice => "Error processing payment"
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  def new
    @payment = Payment.new
  end

  def create
    @payment = current_user.payments.build(:question_id => params[:question_id])
    @payment.payment = true
    
    @question = @payment.question
    @question.response += 1
    @user = current_user
    @user.balance -=1

    if (@payment.save && @question.save && @user.save)
      render "questions/show"
    else
      redirect_to questions_path
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  
  skip_before_filter :require_login, :only => [:new, :create]

  def index
    if params[:tag]
      @questions = Question.tagged_with(params[:tag]).page(params[:page]).per(2)
    else
      @questions = Question.order('questions.created_at DESC').page(params[:page]).per(2)
    end
  end

  def show
    @question = Question.find(params[:id])
  end
  
  def new
    @question = Question.new
  end
 
  def create
    @question = Question.new (params[:question])
    @question.response = 0 #patch fix later
    @question.city = request.location.city
    data = @question
    # Pusher['site-activity'].trigger('action', data)

    if @question.save
      Pusher['test_channel'].trigger('action', data)
      redirect_to root_path, :notice => "Thank you for asking a question! Someone will get back to you shortly!"
    else
      render :new
    end
  end

  def destroy
  end
  
  def edit
  end
  
  def update
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_filter :require_login, :only => [:new,:create]

  def new
  end

  def create
    @user = login(params[:email], params[:password], params[:remember_me])
    if @user
      redirect_to questions_path, :notice => "Logged in!"
    else
      flash.now.alert = "Email or password was invalid."
    end
  end

  def destroy
    logout
    redirect_to root_url, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create, :show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      auto_login(@user)
      redirect_to questions_path, :notice => "Signed up!"
    else
      render :new
    end
  end


  def show
    @user_questions = User.find(params[:id]).questions.order('questions.created_at DESC').page(params[:page]).per(2) 
  end

  def send_message
    # require 'twilio-ruby'
    accountsid = ENV["TWILIO_ACCOUNTS_ID"]
    authtoken = ENV["TWILIO_AUTH_TOKEN"]

    #Text Messaging
    client = Twilio::REST::Client.new(accountsid, authtoken)

    client.account.sms.messages.create(
      :from => '+12898125092',
      :to => params[:number],
      :body => params[:message]
    )
    redirect_to questions_path, :notice => "Message Sent!"

    # Phone Call
    # @client = Twilio::REST::Client.new(accountsid, authtoken)

    # @account = @client.account
    # @call = @account.calls.create({:from => '+12898125092', :to => '4168854959', :url =>"https://demo.twilio.com/welcome/voice/"})
    # puts @call
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/new.html.erb
<%= render "/layouts/nav"%>
<div class="container">
  <div class="add-money">
    <h4>Current Balance: <%=number_to_currency(current_user.balance, :precision =>0)%></h4>
    <h3>Add $10 to Your Balance </h3>

<%= form_tag charges_path, :method => :post do %>

  <script src="https://checkout.stripe.com/v2/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Add Money to Account"
          data-amount="1000"></script>
  <% end %>

  </div>
</div>

<!-- https://stripe.com/docs/checkout/guides/rails -->

app/views/layouts/_nav.html.erb
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <ul class="nav">
      <li class="brand">LeadGen</li>
      <li class="<%= 'active' if current_page? questions_path %>"><%= link_to "Potential Leads", questions_path%></li>

      <li class="<%= 'active' if current_page? user_path(current_user) %>"><%= link_to "My Leads", user_path(current_user)%> </li>

    </ul>
    <ul class="nav pull-right">
      <li><a class="non-link">Account Balance: <%= number_to_currency(current_user.balance, :precision=>0)%></a></li>
      <li class="<%= 'active' if current_page? new_charge_path %>"><%= link_to "Add Money to Account", new_charge_path%></li>
      <li><a class="non-link"> Logged in as <%= current_user.email %></a></li>
      <li>  <%= link_to "Logout", logout_path %></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leadgen</title>

  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>
</body>
</html>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/new.html.erb
<h1>Payments#new</h1>
<p>Find me in app/views/payments/new.html.erb</p>

app/views/questions/index.html.erb
<%= render "/layouts/nav"%>
<div class = "container">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-error">
      <%= flash[:alert] %>
    </div>
  <% end %>
  
  <h1>Potential Leads</h1>

  <!-- http://railscasts.com/episodes/382-tagging?view=asciicast -->

<div class = "list_wrap">
  <% @questions.each do |question|%>
    <div class="list_bg">
      <p>Question: <%= question.description%></p>
      <p class ="tag_overview">Tags: <%= raw question.tag_list.map { |t| link_to t, tag_path(t)}.join(', ')%></p>
      <p>City: <%= question.city%></p>
      <p>Phone: 
        <% if question.phone? %>
          Available
        <%else%>
          Unavailable
        <%end%>
      </p>
      <p>Email: <% if question.email? %>
          Available
        <%else%>
          Unavailable
        <%end%>
      </p>
        <% @purchased = false%>
        <% if current_user.questions == nil %>
          <div class="lead_button"><button class="btn btn-success"><%= link_to "Purchase Lead!", question_path(question)%></button></div>
        <%else%>
          <%current_user.questions.each do |user_question|%>
            <% if user_question.id == question.id%>
                <%@purchased = true%>              
            <%end%>
          <%end%>

          <% if @purchased == true%>
            <div class="lead_button"><button class="btn btn-danger"><%= link_to "Already Purchased!", question_path(question)%></button></div>
          <% else %>
            <div class="lead_button"><button class="btn btn-success"><%= link_to "Purchase Lead!", question_path(question)%></button></div>

          <%end%>
        <%end%>
    </div>
    <br/>
  <%end%>
</div>


<div id="tag_cloud">
  <div class = "tagsinput">
    <% tag_cloud Question.tag_counts, %w{s m l} do |tag, css_class| %>
      <span class="tag"><%= link_to tag.name, tag_path(tag.name), class: css_class %></span>
    <%end%>
      <span class="tag"><%= link_to "All Leads", questions_path%></span>
  </div>
</div>

<div class="live_update">
    
</div>

  <%= paginate @questions %>
</div>

app/views/questions/new.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-error">
    <%= flash[:alert] %>
  </div>
<% end %>
  
<div class="slider_bg fade-in one">Have Tough Financial Questions? </div>
<div class="slider_bg fade-in two"> Get Expert Advice </div>

<a href="#askQuestion" role="button" class="slider_bg fade-in three" data-toggle="modal" >Click Here to Ask a Question</a>

<div id="askQuestion" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="askQuestion" aria-hidden="true">

  <div class="questions_modal">
    <div class="modal-header">
      <h4>Ask a Question! </h4>
    </div>

    <div class="modal-body">
      <%= form_for @question do |f| %>
          <%= f.label "Your Question" %>
          <%= f.text_area :description, :rows => "2", :class=>"span6" %>

          <%= f.label :tag_list, "Tags (separated by commas)" %>
          <%= f.text_field :tag_list, :class=>"span6" %>

        <div class="form-inline">
          <%= f.label :name %>
          <%= f.text_field :name, :class=>"modal_field" %>
        </div><br/>

        <div class="form-inline">
          <%= f.label :phone %>
          <%= f.text_field :phone, :class=>"modal_field_2" %>
        </div><br/>

        <div class="form-inline">
          <%= f.label :email %>
          <%= f.email_field :email, :class=>"modal_field_3" %>
        </div>
    </div>
        <div class="modal-footer">
          <%= f.submit 'Submit Question', :class => 'btn btn-large btn-primary modal_button' %>
        </div>
      <% end %>
  </div>
</div>


<!--  -->
<div class="btn-group pull-right fade-in three">
  <button class="user_registration"><%= link_to "Advisor Sign In", login_path%></button>
  <button class="user_registration"><%= link_to "Advisor Register", new_user_path%></button>
</div>

app/views/questions/show.html.erb
<% check = false%>
  
  <%@question.users.each do |user|%>
    <% if user.id == current_user.id%>
      <% check = true%>
    <%end%>
  <%end%>


<%= render "/layouts/nav"%>

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-error">
      <%= flash[:alert] %>
    </div>
  <% end %>
  
<div class="purchase_group">
  <h3>Purchase Question</h3>
  <p><strong>Question: </strong> <%= @question.description %> </p>
      <% if check == true%>
        <p><strong>Name: </strong> <%= @question.name %> </p>
        <p><strong>Phone: </strong> <%= @question.phone %> </p>
        <p><strong>Email: </strong> <%= @question.email %> </p>
      <%else%>
        <p><strong>Name: </strong> <%=@question.name %> </p>
        <p><strong>Phone: </strong> 
          <% if @question.phone? %> 
            Available
          <%else%>
            Unavailable
          <%end%>
        </p>
        <p><strong>Email: </strong> 
          <% if @question.email? %>
            Available
          <%else%>
            Unavailable 
          <%end%>
        </p>

        <button class="btn btn-primary"><%= link_to "Purchase", question_payments_create_path(@question), :method => :post %></button>

      <%end%>
<br/>



</div>

app/views/users/new.html.erb
<div class="login-group">
  <h1>Register</h1>

  <%= form_for @user, :url => {:action => :create} do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field span4">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>

    <div class="field span4">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    
    <div class="field span4">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
    
    <div class="actions span4"><%= f.submit "Register", :class=>"btn btn-submit" %></div>
  <% end %>
</div>

app/views/users/show.html.erb
<%= render "/layouts/nav"%>
<div class = "container">

  <% if flash[:notice] %>
    <div class="alert alert-success">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-error">
      <%= flash[:alert] %>
    </div>
  <% end %>
  
  <h1>My Leads</h1>
  <div class = "list_wrap">
    <% @user_questions.each do |q| %>
      <div class="list_bg">
        <p>Description:
          <%= q.description%></p>
        <p>name:
          <%= q.name%></p>
        <p>phone:
          <%= q.phone%></p>
        <p>email:
          <%= q.email%></p>
          <p>city:
            <%= q.city%></p>
          </p>
      </div>
    <%end%>
  </div>
  <div id="phone_section">
    TEXT A NUMBER
    
    <%= form_tag users_send_message_path, :method => :post do %>
      <%= label_tag "Phone Number (ex. +14155555555)"%>
      <%= text_field_tag :number %>
      <%= label_tag "Send Message"%>
      <%= text_area_tag :message %>
      <br/>
      <%= submit_tag "Send", :class => "btn btn-success"%>
    <%end%>



  </div>
  <%= paginate(@user_questions)%>
  
  
</div>

<!-- http://stackoverflow.com/questions/10305900/rails-3-pagination-with-kaminari-show-action-of-one-controller-to-browse-re -->